source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NKJPhotoSliderController', :exclusive => true do
  pod "NKJPhotoSliderController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NKJPhotoSliderController", :path => "../"

  pod 'FBSnapshotTestCase'
end
