source 'https://github.com/CocoaPods/Specs.git'

target 'NKJPhotoSliderController' do
  pod "NKJPhotoSliderController", :path => "../"
end

target 'NKJPhotoSliderControllerUITests' do
  pod "NKJPhotoSliderController", :path => "../"
end

