source 'https://github.com/CocoaPods/Specs.git'

target 'NKJPhotoSliderController', :exclusive => true do
  pod "NKJPhotoSliderController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NKJPhotoSliderController", :path => "../"
  pod 'KIF', '~> 3.0', :configurations => ['Debug']
end
